version: '3'
services:
# Database service
    db:
        image: mysql:5.7
        volumes: 
            - db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cokgizlisifre
            MYSQL_DATABASE: wordpress
            MYSQL_USER: murataksu
            MYSQL_PASSWORD: birikiuc123!
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.hostname == node1]
        networks:
            - backend

# Wordpress Service

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8080:80"
        restart: always
        volumes:
            - /var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: murataksu
            WORDPRESS_DB_PASSWORD: birikiuc123!
        deploy:
            replicas: 5
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == worker]
        networks:
            - frontend
            - backend
#PHP My Admin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        restart: always
        ports:
            - "7080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: cokgizlisifre
        networks:
            - frontend
            - backend

#Drupal Service

    drupal:
        image: drupal:latest
        depends_on:
            - db
        ports:
            - "9080:80" 
        volumes:
            - /var/www/html/sites
            - /var/www/html/profiles
            - /var/www/html/themes
            - /var/www/html/modules
            - /var/www/private
        environment:
            MYSQL_PASSWORD: birikiuc123!
            MYSQL_DATABASE: drupal
            MYSQL_USER: murataksu
        deploy:
            replicas: 3
        networks:
            - frontend
            - backend
#Visualizer
    visualizer:
        image: dockersamples/visualizer
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock        
        ports:
            - "6080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]

#Networks and Volumes

networks:
    frontend:
    backend:
volumes:
    db-data:


